from info.views.auth import add_student, add_teacher, index
from info.views.student import attendance, attendance_detail, marks_list, timetable
from info.views.teacher import (
    cancel_class,
    change_att,
    confirm,
    e_confirm,
    edit_att,
    edit_marks,
    free_teachers,
    marks_confirm,
    student_marks,
    t_attendance,
    t_attendance_detail,
    t_class_date,
    t_clas,
    t_extra_class,
    t_marks_entry,
    t_marks_list,
    t_report,
    t_student,
    t_timetable,
)

__all__ = [
    'index',
    'attendance',
    'attendance_detail',
    'timetable',
    'marks_list',
    't_clas',
    't_student',
    't_class_date',
    'cancel_class',
    't_attendance',
    'edit_att',
    'confirm',
    't_attendance_detail',
    'change_att',
    't_extra_class',
    'e_confirm',
    't_report',
    't_timetable',
    'free_teachers',
    't_marks_list',
    't_marks_entry',
    'marks_confirm',
    'edit_marks',
    'student_marks',
    'add_teacher',
    'add_student',
]
